version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-246-100-246.eu-west-1.compute.amazonaws.com
            database: d6pvnn87g0kojq
            user: gsoqfrtnxsropx
            password: 9a6920dc2413d74fb912364de47885f015a83c66d7d082dd4c59bf140fbc25fb
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true